"""Initial migration

Revision ID: 8b053cd1dd70
Revises: 
Create Date: 2024-05-23 08:41:50.285069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b053cd1dd70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('books', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.drop_column('books', 'file_path')
    op.drop_column('books', 'cover_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover_url', sa.VARCHAR(), nullable=True))
    op.add_column('books', sa.Column('file_path', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_column('books', 'file_data')
    op.drop_column('books', 'file_name')
    # ### end Alembic commands ###
